defaults:
  - view_sampler: bounded

name: scannet
make_baseline_1: false
augment: true
roots: []

original_image_shape: [480, 640]
input_image_shape: [256, 256]
background_color: [0.0, 0.0, 0.0]
cameras_are_circular: false

baseline_epsilon: 1e-3
max_fov: 100.0
load_depth: true
near: 0.5
far: 15.0

overfit_to_scene: null
view_sampler:
  num_context_views: 6
  num_target_views: 2