name: bounded
num_context_views: 6
num_target_views: 2
min_distance_between_context_views: 1
max_distance_between_context_views: 10
min_distance_to_context_views: 1
warm_up_steps: 1000
initial_min_distance_between_context_views: 1
initial_max_distance_between_context_views: 3
max_img_per_gpu: 8
min_gap_multiplier: 1
max_gap_multiplier: 5